### ISSUE TITLE
Question about Usb port

### ISSUE THREAD

**Issue by yaki4** [ArduinoHannover/FlipDot_5x7#2]
Hello,
I've got a question about the controller and how to power my system.
If i check my controller i see a space for what seems to be a barrel power connector. But on the pcb it says usb.
I guess it make more sense to be  barrel power connector since the flipdot need 12v but I lack documentation/knowledge and doesn't wanna make a mistake.

Can you confirm it or guide me to a component suitable for the controller ?

<img width="168" alt="Capture d’écran, le 2021-08-18 à 22 13 04" src="https://user-images.githubusercontent.com/1856630/129996657-6184655d-d6ce-475b-baa4-ef5ecc021797.png">

**Comment by soundstorm** [comment]
It is labeled USB due to the overlaying Arduino Nano footprint (older version, backwards compatibility). So it's a regular 5.5x2.1 barrel jack connector for the 12V input.
